# Generated by Django 5.0.6 on 2025-02-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_function', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pateint',
            new_name='Patient',
        ),
    ]
