# Generated by Django 5.0.6 on 2025-02-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_function', '0002_rename_pateint_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartrate',
            old_name='pateint',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='heartrate',
            old_name='recorder_at',
            new_name='recorded_at',
        ),
    ]
